elasticsearchHosts: http://elasticsearch-master:9200


imageTag: "7.15.0"  #跟es版本得一致

## kibana配置 
kibanaConfig:
  kibana.yml: |
    i18n.locale: "zh-CN"

## es用户名和密码
extraEnvs:
  - name: NODE_OPTIONS
    value: --max-old-space-size=1800
  - name: ELASTICSEARCH_USERNAME
    valueFrom:
      secretKeyRef:
        key: username
        name: elastic-credentials
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: elastic-credentials


## 资源配置
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 2Gi
