apiVersion: v1
kind: ConfigMap
metadata:
  name: es-template
data:
  index_template.json: |-
    {
        "index_patterns": [
            "logstash-*"
        ],
        "settings": {
            "index": {
                "number_of_shards": "3",
                "number_of_replicas": "0"
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  containers.conf: |
      <source>
        @type tail
        @id in_tail_container_logs
        path "#{ENV['FLUENT_CONTAINER_TAIL_PATH'] || '/var/log/containers/*.log'}"
        pos_file /var/log/fluentd-containers.log.pos
        tag "#{ENV['FLUENT_CONTAINER_TAIL_TAG'] || 'kubernetes.*'}"
        exclude_path "#{ENV['FLUENT_CONTAINER_TAIL_EXCLUDE_PATH'] || use_default}"
        read_from_head true
        @include ../tail_container_parse.conf
      </source>
