apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  namespace: spotmax-maxcloud
spec:
  selector:
    matchLabels:
      app: grafana-deploy
  template:
    metadata:
      labels:
        app: grafana-deploy
    spec:
      containers:
        - name: grafana-deploy
          image: registry.cn-hongkong.aliyuncs.com/spotmax/maxcloud-grafana:8.1.0-aliyun
          resources:
            limits:
              memory: "1024Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: spotmax-maxcloud
spec:
  selector:
    app: grafana-deploy
  ports:
    - port: 3000
      targetPort: 3000