apiVersion: apps/v1
kind: Deployment
metadata:
  name: activator
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
        - name: activator
          resources:
            requests:
              cpu: 0
              memory: 0
